package swp.group5.swp_interior_project.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import swp.group5.swp_interior_project.model.enums.AccountRole;
import swp.group5.swp_interior_project.model.enums.RequestStatus;
import swp.group5.swp_interior_project.service.interfaces.RequestService;
import swp.group5.swp_interior_project.service.interfaces.UserInfoService;

import java.util.List;

@RestController
@RequestMapping("/api/v1/dashboard")
public class DashboardController {
    private final RequestService requestService;
    private final UserInfoService userInfoService;
    
    @Autowired
    public DashboardController(RequestService requestService, UserInfoService userInfoService) {
        this.requestService = requestService;
        this.userInfoService = userInfoService;
    }
    
    /**
     * API Endpoint: /api/v1/dashboard/employee-revenue-by-month
     * Method: GET
     * Description: Retrieves the revenue generated by each employee for the current month.
     * Expected Output: A list of Object arrays containing staff names and their respective total revenue for the current month.
     */
    @GetMapping("/employee-revenue-by-month")
    public List<Object[]> getEmployeeRevenueByMonth() {
        return userInfoService.findStaffAndTotalPriceByRoleAndStatus(AccountRole.ROLE_STAFF, RequestStatus.CONSTRUCTION_IN_PROGRESS);
    }
    
    /**
     * API Endpoint: /api/v1/dashboard/monthly-total-price
     * Method: GET
     * Description: Retrieves the total price of requests for each month.
     * Expected Output: A ResponseEntity containing a list of Object arrays representing monthly total prices.
     */
    @GetMapping("/monthly-total-price")
    public ResponseEntity<List<Object[]>> getMonthlyTotalPrice() {
        List<Object[]> monthlyTotalPriceList = requestService.getMonthlyTotalPrice();
        return new ResponseEntity<>(monthlyTotalPriceList, HttpStatus.OK);
    }
    
    /**
     * API Endpoint: /api/v1/dashboard/average-last-7-days
     * Method: GET
     * Description: Retrieves the average waiting time for requests over the last 7 days.
     * Expected Output: A ResponseEntity containing a list of Object arrays representing the average waiting time for each day.
     */
    @GetMapping("/average-last-7-days")
    public ResponseEntity<?> getAverageWaitingTimeForLast7Days() {
        List<Object[]> result = requestService.getAverageWaitingTimeForLast7Days();
        return ResponseEntity.ok(result);
    }
}
